import type { QuestMapData } from "../types/game";

// Helper to create tile grids
function makeGrid(rows: string[]): QuestMapData["tiles"] {
  const tileMap: Record<string, QuestMapData["tiles"][0][0]> = {
    "G": "grass", "P": "path", "W": "water", "M": "mountain",
    "F": "forest", "T": "town", "C": "cave", "L": "lava",
  };
  return rows.map(row => row.split("").map(c => tileMap[c] || "grass"));
}

export const QUEST_MAPS: Record<string, QuestMapData> = {
  "Hub Town": {
    name: "Hub Town",
    width: 25, height: 20,
    tiles: makeGrid([
      "WWWWWWWWWWWWWWWWWWWWWWWWW",
      "WTTTTTTTTTTTTTTTTTTTTTTTW",
      "WTGGGGGGGGGGGGGGGGGGGGGTW",
      "WTGGGGGGGGGGGGGGGGGGGGGTW",
      "WTGGGGPPPPPPPPPPPGEGGGTW",
      "WTGGGGPGGGGGGGGGGGEGGGTW",
      "WTGGGGPGGGGGGGGGGGEGGGTW",
      "PPPPPPPPPPPPPPPPPPPPPPPPP",
      "WTGGGGPGGGGGGGGGGGEGGGTW",
      "WTGGGGPGGGGGGGGGGGEGGGTW",
      "WTGGGGPPPPPPPPPPPGEGGGTW",
      "WTGGGGGGGGGGGGGGGGGGGGGTW",
      "WTGGGGGGGGGGGGGGGGGGGGGTW",
      "WTGGGGFFFFFFFFFFFGEGGGTW",
      "WTGGGGFFFFFFFFFFFGEGGGTW",
      "WTGGGGFFFFFFFFFFFGEGGGTW",
      "WTGGGGFFFFFFFFFFFGEGGGTW",
      "WTGGGGGGGGGGGGGGGGGGGGGTW",
      "WTTTTTTTTTTTTTTTTTTTTTTTW",
      "WWWWWWWWWWWWWWWWWWWWWWWWW",
    ]),
    playerStart: { x: 12, y: 7 },
    npcs: [
      { id: "elder-hub", name: "Grand Elder", position: { x: 12, y: 3 }, sprite: "elder",
        dialog: ["Welcome to Vibe City, traveler.", "We have many tasks for someone of your talent.", "I can guide you to some basic training if you wish."],
      },
      { id: "cleric-hub", name: "High Priestess", position: { x: 2, y: 7 }, sprite: "priest",
        dialog: ["The light shines upon you.", "Our monastery seeks help with some spiritual matters.", "Speak with me if you follow the path of the priest."],
        questId: "priest-plague",
      },
      { id: "knight-hub", name: "Captain of the Guard", position: { x: 22, y: 7 }, sprite: "knight",
        dialog: ["Keep your weapon ready, soldier.", "There are monsters causing trouble on the trade routes.", "Warriors should report to me for duty!"],
        questId: "warrior-village",
      },
      { id: "wizard-hub", name: "Archmage", position: { x: 12, y: 15 }, sprite: "wizard",
        dialog: ["I sense great potential in you.", "Magical anomalies have been detected in the Whispering Woods.", "Mages who seek knowledge should talk to me."],
        questId: "mage-apprentice",
      },
    ],
  },
  "Northern Village": {
    name: "Northern Village",
    width: 12, height: 10,
    tiles: makeGrid([
      "FFGGGGTTTTFF",
      "FGPPPPPPTGFF",
      "GGPGGGGPPGGG",
      "GGPGGGGGGPGG",
      "PPPPGGGGGGPG",
      "GGPGGGWWWGPG",
      "GGPGGWWWWGPP",
      "GGPPPPPPPPGG",
      "FGGGGGGGGGGG",
      "FFGGGGGGGGFF",
    ]),
    playerStart: { x: 1, y: 4 },
    npcs: [
      { id: "elder", name: "Village Elder", position: { x: 6, y: 1 }, sprite: "elder",
        dialog: ["Welcome, adventurer. Our village is in danger.", "Strange forces threaten our people.", "Will you help us? Speak with the guards to learn more."],
      },
      { id: "guard", name: "Gate Guard", position: { x: 3, y: 3 }, sprite: "guard",
        dialog: ["Halt! The road ahead is dangerous.", "We've spotted enemies approaching from the north.", "We need a brave warrior to defend our gates!"],
        questId: "warrior-village",
      },
      { id: "merchant-nv", name: "Traveling Merchant", position: { x: 8, y: 2 }, sprite: "merchant",
        dialog: ["Greetings! I have wares if you're interested.", "Be careful out there — dark times ahead."],
      },
    ],
  },

  "Whispering Woods": {
    name: "Whispering Woods",
    width: 12, height: 10,
    tiles: makeGrid([
      "FFFFFFGGFFFF",
      "FFPPPFGFFFPF",
      "FPPFFGGFFPPF",
      "FPFFFFFFGFPF",
      "FPFFFFFFGFPF",
      "FPFGGFFFFPPF",
      "FPPGGFFFFFPF",
      "FFPPPPPPPPFF",
      "FFFGGGGGFFFF",
      "FFFFFFFFFFFF",
    ]),
    playerStart: { x: 2, y: 7 },
    npcs: [
      { id: "fairy-w", name: "Forest Fairy", position: { x: 5, y: 3 }, sprite: "fairy",
        dialog: ["The woods whisper of a lost apprentice...", "Their magical aura can still be felt deep within.", "Find them before the forest claims them!"],
        questId: "mage-apprentice",
      },
      { id: "wizard-w", name: "Forest Sage", position: { x: 9, y: 1 }, sprite: "wizard",
        dialog: ["I sensed wild magic from the old library.", "It must be contained before it spreads.", "Only a skilled mage can handle this."],
        questId: "mage-library",
      },
    ],
  },

  "Mountain Pass": {
    name: "Mountain Pass",
    width: 12, height: 10,
    tiles: makeGrid([
      "MMMMGGGGMMMM",
      "MMGPPPPGGMMM",
      "MGPPMMMPGMMM",
      "GGPMMMMPGGGM",
      "PPPMMMMMPPPG",
      "GGPMMMMPGGGM",
      "MGPPMMMPGGMM",
      "MMGPPPPPPGMM",
      "MMMGGGGGGMMM",
      "MMMMMMMMMMMM",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "miner", name: "Frightened Miner", position: { x: 7, y: 1 }, sprite: "villager",
        dialog: ["Something massive has awakened in the mountain!", "An elemental of pure earth blocks the road!", "We need magical help to deal with it!"],
        questId: "mage-elemental",
      },
    ],
  },

  "Trade Route": {
    name: "Trade Route",
    width: 12, height: 10,
    tiles: makeGrid([
      "GGFFFFFFFGGG",
      "GPPPPPPPPPGG",
      "GGFFFFFFFGGG",
      "GFFGGGGGFFGG",
      "GFFGGGGGFFGG",
      "GFFGGGGGFFPG",
      "GGFFFFFFFGPG",
      "GPPPPPPPPPPP",
      "GGGGGGGGGGGG",
      "GGGGGGGGGGGG",
    ]),
    playerStart: { x: 1, y: 1 },
    npcs: [
      { id: "merchant-tr", name: "Scared Merchant", position: { x: 6, y: 1 }, sprite: "merchant",
        dialog: ["Please help! Wolves have made a nest near the road!", "They attack anyone who passes by!", "We need someone strong to clear the way!"],
        questId: "warrior-monster",
      },
    ],
  },

  "Training Grounds": {
    name: "Training Grounds",
    width: 12, height: 10,
    tiles: makeGrid([
      "GGTTTTTTTTGG",
      "GPPPPPPPPPPG",
      "GPGGGGGGGGPG",
      "GPGGPPPPGGPG",
      "GPGGPGGPGGPG",
      "GPGGPGGPGGPG",
      "GPGGPPPPGGPG",
      "GPGGGGGGGGPG",
      "GPPPPPPPPPPG",
      "GGGGGGGGGGGG",
    ]),
    playerStart: { x: 1, y: 8 },
    npcs: [
      { id: "knight-tg", name: "Honor Knight", position: { x: 5, y: 4 }, sprite: "knight",
        dialog: ["You dare enter my arena?", "Only the strongest may challenge me!", "Prove your worth in combat, warrior!"],
        questId: "warrior-duel",
      },
    ],
  },

  "Dark Forest": {
    name: "Dark Forest",
    width: 12, height: 10,
    tiles: makeGrid([
      "FFFFFFFFFFFF",
      "FFPPPFFFPPFF",
      "FPPFFFGFFPFF",
      "FPFFFFFFGPFF",
      "FPFFFFFFGPFF",
      "FPFGGGFFFPFF",
      "FPPGGGFFFFPF",
      "FFPPPPPPPPFF",
      "FFFFFFFFFFFF",
      "FFFFFFFFFFFF",
    ]),
    playerStart: { x: 2, y: 7 },
    npcs: [
      { id: "scout-df", name: "Village Scout", position: { x: 5, y: 5 }, sprite: "guard",
        dialog: ["I've been tracking the orc war camp!", "Their chieftain is camped just ahead.", "Be careful — they're well armed!"],
        questId: "warrior-orc-camp",
      },
    ],
  },

  "Dragon Peak": {
    name: "Dragon Peak",
    width: 12, height: 10,
    tiles: makeGrid([
      "MMMMMMMMLLMM",
      "MMMMPPPPLMMM",
      "MMPPMMMPLMMM",
      "MPPMMMMPLLMM",
      "PPPMMMMPLLMM",
      "MPPMMMMPMMML",
      "MMPPMMPPMMML",
      "MMMPPPPMMMMM",
      "MMMMMMMMMMMM",
      "MMMMMMMMMMMM",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "hermit-dp", name: "Mountain Hermit", position: { x: 4, y: 1 }, sprite: "elder",
        dialog: ["You seek the wyvern? It nests at the peak.", "The path is treacherous, but a true warrior finds a way.", "Use the terrain wisely, young one!"],
        questId: "warrior-dragon-lair",
      },
    ],
  },

  "Southern Village": {
    name: "Southern Village",
    width: 12, height: 10,
    tiles: makeGrid([
      "GGTTTTTTGGGG",
      "GPPPPPPPPGGG",
      "GPGGGGGGGPWW",
      "GPGGTTGGGGWW",
      "PPPPPPPPPPWW",
      "GPGGTTGGGGWW",
      "GPGGGGGGGPWW",
      "GPPPPPPPPGWW",
      "GGGGGGGGGGGG",
      "GGGGGGGGGGGG",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "healer-sv", name: "Village Healer", position: { x: 5, y: 3 }, sprite: "priest",
        dialog: ["The plague is spreading fast!", "I need someone with healing magic to help.", "Can you purify the water source?"],
        questId: "priest-plague",
      },
    ],
  },

  "Abandoned Church": {
    name: "Abandoned Church",
    width: 12, height: 10,
    tiles: makeGrid([
      "GGCCCCCCGGGG",
      "GCPPPPPPPPGG",
      "GCPCCCCCCPGG",
      "GCPCCCCCCPGG",
      "PPPPCCCCPPGG",
      "GCPCCCCCCPGG",
      "GCPCCCCCCPGG",
      "GCPPPPPPPPGG",
      "GGCCCCCCGGGG",
      "GGGGGGGGGGGG",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "spirit-ac", name: "Monastery Keeper", position: { x: 6, y: 4 }, sprite: "elder",
        dialog: ["The old church has been haunted for years.", "A restless spirit wanders its halls.", "Only divine light can bring it peace."],
        questId: "priest-ghost",
      },
    ],
  },

  "Sacred Catacombs": {
    name: "Sacred Catacombs",
    width: 12, height: 10,
    tiles: makeGrid([
      "CCCCCCCCCCCC",
      "CPPPPPPPPPPPC",
      "CPCCCCCCCCPC",
      "CPCCPPPPCCPC",
      "PPCCPCCPCCPP",
      "CPCCPPPPCCPC",
      "CPCCCCCCCCPC",
      "CPPPPPPPPPPPC",
      "CCCCCCCCCCCC",
      "CCCCCCCCCCCC",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "priest-sc", name: "Tomb Guardian", position: { x: 5, y: 3 }, sprite: "priest",
        dialog: ["The undead have broken free from their crypts!", "Powerful necromantic energy fills these halls.", "Your divine power is needed to seal them!"],
        questId: "priest-undead-crypt",
      },
    ],
  },

  "Cursed Ruins": {
    name: "Cursed Ruins",
    width: 12, height: 10,
    tiles: makeGrid([
      "CCLLLLLLCCCC",
      "CPPPPPPPPCCC",
      "CPCCCLLCCPCC",
      "CPCCLLLCCPCC",
      "PPCCLLLLCPPCC",
      "CPCCLLLCCPCC",
      "CPCCCLLCCPCC",
      "CPPPPPPPPCCC",
      "CCCCCCCCCCCC",
      "CCCCCCCCCCCC",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "angel-cr", name: "Fallen Angel", position: { x: 5, y: 1 }, sprite: "fairy",
        dialog: ["A demon portal has opened in the ruins below!", "Hellfire spews forth, corrupting everything.", "You must channel divine power to seal it forever!"],
        questId: "priest-demon-portal",
      },
    ],
  },

  "Crystal Caverns": {
    name: "Crystal Caverns",
    width: 12, height: 10,
    tiles: makeGrid([
      "CCCCCCCCCCCC",
      "CPPPPPPPPPPPC",
      "CPCCCCCCCCPC",
      "CPCCPPPPCCPC",
      "PPCCPCCPCCPP",
      "CPCCPPPPCCPC",
      "CPCCCCCCCCPC",
      "CPPPPPPPPPPPC",
      "CCCCCCCCCCCC",
      "CCCCCCCCCCCC",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "miner-cc", name: "Crystal Miner", position: { x: 5, y: 3 }, sprite: "villager",
        dialog: ["Strange crystals have been growing everywhere!", "They attract dangerous magical creatures.", "Can you use your magic to help us?"],
        questId: "mage-crystalcave",
      },
    ],
  },

  "Shadow Tower": {
    name: "Shadow Tower",
    width: 12, height: 10,
    tiles: makeGrid([
      "FFFFCCCCFFFF",
      "FFPPPPPPPPFF",
      "FPCCCCCCCCPF",
      "FPCCPPPPCCPF",
      "PPCCPCCPCCPP",
      "FPCCPPPPCCPF",
      "FPCCCCCCCCPF",
      "FFPPPPPPPPFF",
      "FFFFCCCCFFFF",
      "FFFFFFFFFFFF",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "wizard-st", name: "Tower Sentinel", position: { x: 5, y: 1 }, sprite: "wizard",
        dialog: ["A rogue mage has seized the watchtower!", "His experiments threaten the entire region.", "Only another mage can challenge him!"],
        questId: "mage-tower",
      },
    ],
  },
};

export function getQuestMap(region: string): QuestMapData | null {
  return QUEST_MAPS[region] || null;
}
