import type { QuestMapData } from "../types/game";

// Helper to create tile grids
function makeGrid(rows: string[]): QuestMapData["tiles"] {
  const tileMap: Record<string, QuestMapData["tiles"][0][0]> = {
    "G": "grass", "P": "path", "W": "water", "M": "mountain",
    "F": "forest", "T": "town", "C": "cave", "L": "lava",
  };
  return rows.map(row => row.split("").map(c => tileMap[c] || "grass"));
}

export const QUEST_MAPS: Record<string, QuestMapData> = {
  "Hub Town": {
    name: "Hub Town",
    width: 15, height: 12,
    tiles: makeGrid([
      "GGGGGGGGGGGGGGG",
      "GTTTTTTTTTTTTTG",
      "GTGGGGGGGGGGGTG",
      "GTGTTTTTTTTGGGTG",
      "GTGTPPPPPPTGGGTG",
      "GTGTPGGGPTGGGTG",
      "GTGTPGGGPTGGGTG",
      "GTGTPPPPPPTGGGTG",
      "GTGGGGGGGGGGGTG",
      "GTGGFFFFFFFFFFGTG",
      "GTGGFFFFFFFFFFGTG",
      "GGGGGGGGGGGGGGG",
    ]),
    playerStart: { x: 7, y: 6 },
    npcs: [
      { id: "elder-hub", name: "Grand Elder", position: { x: 7, y: 2 }, sprite: "elder",
        dialog: ["Welcome to Vibe City, traveler.", "We have many tasks for someone of your talent.", "I can guide you to some basic training if you wish."],
      },
      { id: "cleric-hub", name: "High Priestess", position: { x: 2, y: 5 }, sprite: "priest",
        dialog: ["The light shines upon you.", "Our monastery seeks help with some spiritual matters.", "Speak with me if you follow the path of the priest."],
        questId: "priest-plague",
      },
      { id: "knight-hub", name: "Captain of the Guard", position: { x: 12, y: 5 }, sprite: "knight",
        dialog: ["Keep your weapon ready, soldier.", "There are monsters causing trouble on the trade routes.", "Warriors should report to me for duty!"],
        questId: "warrior-village",
      },
      { id: "wizard-hub", name: "Archmage", position: { x: 7, y: 9 }, sprite: "wizard",
        dialog: ["I sense great potential in you.", "Magical anomalies have been detected in the Whispering Woods.", "Mages who seek knowledge should talk to me."],
        questId: "mage-apprentice",
      },
      { id: "guild-master", name: "Guild Master", position: { x: 10, y: 5 }, sprite: "knight",
        dialog: ["Greetings, adventurer! You look like you've seen some battles.", "The Adventurer's Guild is always looking for talent.", "With enough gold and experience, I can help you reach a new rank!"],
      },
    ],
  },
  "Northern Village": {
    name: "Northern Village",
    width: 12, height: 10,
    tiles: makeGrid([
      "FFFFFFFFFFFF",
      "FFTTTTTTTFFF",
      "FTGGGGGGGTFF",
      "FTGPPPPGPPFF",
      "FTGPGGGPGGFF",
      "FTGPGGGPGGFF",
      "FTGPPPPGGGFF",
      "FTGGGGGGGGFF",
      "FFTTTTTTTTFF",
      "FFFFFFFFFFFF",
    ]),
    playerStart: { x: 1, y: 4 },
    npcs: [
      { id: "elder", name: "Village Elder", position: { x: 6, y: 2 }, sprite: "elder",
        dialog: ["Welcome, adventurer. Our village is in danger.", "Strange forces threaten our people.", "Will you help us? Speak with the guards to learn more."],
      },
      { id: "guard", name: "Gate Guard", position: { x: 3, y: 4 }, sprite: "guard",
        dialog: ["Halt! The road ahead is dangerous.", "We've spotted enemies approaching from the north.", "We need a brave warrior to defend our gates!"],
        questId: "warrior-village",
      },
      { id: "merchant-nv", name: "Traveling Merchant", position: { x: 8, y: 3 }, sprite: "merchant",
        dialog: ["Greetings! I have wares if you're interested.", "Be careful out there — dark times ahead."],
      },
      { id: "priest-nv", name: "Village Priest", position: { x: 5, y: 1 }, sprite: "priest",
        dialog: ["The village needs protection from evil.", "A grand blessing ritual is required.", "Can you perform it?"],
        questId: "priest-blessing",
      },
    ],
  },

  "Whispering Woods": {
    name: "Whispering Woods",
    width: 12, height: 10,
    tiles: makeGrid([
      "FFFFFFFFFFFF",
      "FFFFFFFFFFFF",
      "FFFGFFFFGFFF",
      "FFGPGFFFGPFF",
      "FFPFFFFFFPFF",
      "FFPFFFFFFPFF",
      "FFGPGFFFGPFF",
      "FFFGFFFFGFFF",
      "FFFFFFFFFFFF",
      "FFFFFFFFFFFF",
    ]),
    playerStart: { x: 2, y: 7 },
    npcs: [
      { id: "fairy-w", name: "Forest Fairy", position: { x: 5, y: 3 }, sprite: "fairy",
        dialog: ["The woods whisper of a lost apprentice...", "Their magical aura can still be felt deep within.", "Find them before the forest claims them!"],
        questId: "mage-apprentice",
      },
      { id: "wizard-w", name: "Forest Sage", position: { x: 9, y: 1 }, sprite: "wizard",
        dialog: ["I sensed wild magic from the old library.", "It must be contained before it spreads.", "Only a skilled mage can handle this."],
        questId: "mage-library",
      },
    ],
  },

  "Mountain Pass": {
    name: "Mountain Pass",
    width: 12, height: 10,
    tiles: makeGrid([
      "MMMMMMMMMMMM",
      "MMGGGGGGGGMM",
      "MGPPPPPPPGMM",
      "MGPGMMMGPGMM",
      "MGPGMMMGPGMM",
      "MGPGMMMGPGMM",
      "MGPGMMMGPGMM",
      "MGPPPPPPPGMM",
      "MMGGGGGGGGMM",
      "MMMMMMMMMMMM",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "miner", name: "Frightened Miner", position: { x: 7, y: 1 }, sprite: "villager",
        dialog: ["Something massive has awakened in the mountain!", "An elemental of pure earth blocks the road!", "We need magical help to deal with it!"],
        questId: "mage-elemental",
      },
    ],
  },

  "Trade Route": {
    name: "Trade Route",
    width: 12, height: 10,
    tiles: makeGrid([
      "GGGGGGGGGGGG",
      "GGPPPPPPPPGG",
      "GGPGFFFFFPGG",
      "GGPGFFFFFPGG",
      "GGPGFFFFFPGG",
      "GGPGFFFFFPGG",
      "GGPGFFFFFPGG",
      "GGPPPPPPPPGG",
      "GGGGGGGGGGGG",
      "GGGGGGGGGGGG",
    ]),
    playerStart: { x: 1, y: 1 },
    npcs: [
      { id: "merchant-tr", name: "Scared Merchant", position: { x: 6, y: 1 }, sprite: "merchant",
        dialog: ["Please help! Wolves have made a nest near the road!", "They attack anyone who passes by!", "We need someone strong to clear the way!"],
        questId: "warrior-monster",
      },
    ],
  },

  "Training Grounds": {
    name: "Training Grounds",
    width: 12, height: 10,
    tiles: makeGrid([
      "GGGGGGGGGGGG",
      "GPPPPPPPPPPG",
      "GPGTTTTTTGPG",
      "GPGTPPPPTGPG",
      "GPGTPGPTGPG",
      "GPGTPGPTGPG",
      "GPGTPPPPTGPG",
      "GPGTTTTTTGPG",
      "GPPPPPPPPPPG",
      "GGGGGGGGGGGG",
    ]),
    playerStart: { x: 1, y: 8 },
    npcs: [
      { id: "knight-tg", name: "Honor Knight", position: { x: 5, y: 4 }, sprite: "knight",
        dialog: ["You dare enter my arena?", "Only the strongest may challenge me!", "Prove your worth in combat, warrior!"],
        questId: "warrior-duel",
      },
    ],
  },

  "Dark Forest": {
    name: "Dark Forest",
    width: 12, height: 10,
    tiles: makeGrid([
      "FFFFFFFFFFFF",
      "FFFFFFFFFFFF",
      "FFFGFFFFGFFF",
      "FFGPGFFFGPFF",
      "FFPFFFFFFPFF",
      "FFPFFFFFFPFF",
      "FFGPGFFFGPFF",
      "FFFGFFFFGFFF",
      "FFFFFFFFFFFF",
      "FFFFFFFFFFFF",
    ]),
    playerStart: { x: 2, y: 7 },
    npcs: [
      { id: "scout-df", name: "Village Scout", position: { x: 5, y: 5 }, sprite: "guard",
        dialog: ["I've been tracking the orc war camp!", "Their chieftain is camped just ahead.", "Be careful — they're well armed!"],
        questId: "warrior-orc-camp",
      },
    ],
  },

  "Dragon Peak": {
    name: "Dragon Peak",
    width: 12, height: 10,
    tiles: makeGrid([
      "MMMMMMMMMMMM",
      "MMMMGGGGMMMM",
      "MMGPPPPGGMMM",
      "MGPGMMMGPGMM",
      "MGPGMMMGPGMM",
      "MGPGMMMGPGMM",
      "MGPGMMMGPGMM",
      "MMGPPPPGGMMM",
      "MMMMGGGGMMMM",
      "MMMMMMMMMMMM",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "hermit-dp", name: "Mountain Hermit", position: { x: 4, y: 1 }, sprite: "elder",
        dialog: ["You seek the wyvern? It nests at the peak.", "The path is treacherous, but a true warrior finds a way.", "Use the terrain wisely, young one!"],
        questId: "warrior-dragon-lair",
      },
    ],
  },

  "Southern Village": {
    name: "Southern Village",
    width: 12, height: 10,
    tiles: makeGrid([
      "GGGGGGGGGGGG",
      "GPPPPPPPPPPG",
      "GPGTTTTTTGPG",
      "GPGTPPPPTGPG",
      "GPGTPGPTGPG",
      "GPGTPGPTGPG",
      "GPGTPPPPTGPG",
      "GPGTTTTTTGPG",
      "GPPPPPPPPPPG",
      "GGGGGGGGGGGG",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "healer-sv", name: "Village Healer", position: { x: 5, y: 3 }, sprite: "priest",
        dialog: ["The plague is spreading fast!", "I need someone with healing magic to help.", "Can you purify the water source?"],
        questId: "priest-plague",
      },
    ],
  },

  "Abandoned Church": {
    name: "Abandoned Church",
    width: 12, height: 10,
    tiles: makeGrid([
      "GGGGGGGGGGGG",
      "GGCCCCCCGGGG",
      "GGCPPPPCGGGG",
      "GGCPPPPCGGGG",
      "GGCPPPPCGGGG",
      "GGCPPPPCGGGG",
      "GGCPPPPCGGGG",
      "GGCPPPPCGGGG",
      "GGCCCCCCGGGG",
      "GGGGGGGGGGGG",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "spirit-ac", name: "Monastery Keeper", position: { x: 6, y: 4 }, sprite: "elder",
        dialog: ["The old church has been haunted for years.", "A restless spirit wanders its halls.", "Only divine light can bring it peace."],
        questId: "priest-ghost",
      },
    ],
  },

  "Sacred Catacombs": {
    name: "Sacred Catacombs",
    width: 12, height: 10,
    tiles: makeGrid([
      "CCCCCCCCCCCC",
      "CPPPPPPPPPPC",
      "CPCGGGGGGCPC",
      "CPCGCCCCGCPC",
      "CPCGCCCCGCPC",
      "CPCGCCCCGCPC",
      "CPCGCCCCGCPC",
      "CPCGGGGGGCPC",
      "CPPPPPPPPPPC",
      "CCCCCCCCCCCC",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "priest-sc", name: "Tomb Guardian", position: { x: 5, y: 3 }, sprite: "priest",
        dialog: ["The undead have broken free from their crypts!", "Powerful necromantic energy fills these halls.", "Your divine power is needed to seal them!"],
        questId: "priest-undead-crypt",
      },
    ],
  },

  "Cursed Ruins": {
    name: "Cursed Ruins",
    width: 12, height: 10,
    tiles: makeGrid([
      "CCCCCCCCCCCC",
      "CLLLLLLLLLLC",
      "CLCGGGGGGCLC",
      "CLCGCCCCGCLC",
      "CLCGCCCCGCLC",
      "CLCGCCCCGCLC",
      "CLCGCCCCGCLC",
      "CLCGGGGGGCLC",
      "CLLLLLLLLLLC",
      "CCCCCCCCCCCC",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "angel-cr", name: "Fallen Angel", position: { x: 5, y: 1 }, sprite: "fairy",
        dialog: ["A demon portal has opened in the ruins below!", "Hellfire spews forth, corrupting everything.", "You must channel divine power to seal it forever!"],
        questId: "priest-demon-portal",
      },
    ],
  },

  "Crystal Caverns": {
    name: "Crystal Caverns",
    width: 12, height: 10,
    tiles: makeGrid([
      "CCCCCCCCCCCC",
      "CGGGGGGGGGGC",
      "CGCPPPPPPCGC",
      "CGCPCGGPCGC",
      "CGCPCGGPCGC",
      "CGCPCGGPCGC",
      "CGCPCGGPCGC",
      "CGCPPPPPPCGC",
      "CGGGGGGGGGGC",
      "CCCCCCCCCCCC",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "miner-cc", name: "Crystal Miner", position: { x: 5, y: 3 }, sprite: "villager",
        dialog: ["Strange crystals have been growing everywhere!", "They attract dangerous magical creatures.", "Can you use your magic to help us?"],
        questId: "mage-crystalcave",
      },
    ],
  },

  "Shadow Tower": {
    name: "Shadow Tower",
    width: 12, height: 10,
    tiles: makeGrid([
      "FFFFFFFFFFFF",
      "FCCCCCCCCCCF",
      "FCGGGGGGGGCF",
      "FCGPPPPPPGCF",
      "FCGPGCCPGGCF",
      "FCGPGCCPGGCF",
      "FCGPPPPPPGCF",
      "FCGGGGGGGGCF",
      "FCCCCCCCCCCF",
      "FFFFFFFFFFFF",
    ]),
    playerStart: { x: 0, y: 4 },
    npcs: [
      { id: "wizard-st", name: "Tower Sentinel", position: { x: 5, y: 1 }, sprite: "wizard",
        dialog: ["A rogue mage has seized the watchtower!", "His experiments threaten the entire region.", "Only another mage can challenge him!"],
        questId: "mage-tower",
      },
    ],
  },

  "Capital City": {
    name: "Capital City",
    width: 12, height: 10,
    tiles: makeGrid([
      "FFFFCFFFFFFF",
      "FCCCTTTCCCCF",
      "FCTTTTTTTTTC",
      "CCTTTTTTTTTC",
      "CCTTTTHTTTTC",
      "CCTTTTTTTTTC",
      "FCTTTTTTTTTC",
      "FCCCTTTCCCCF",
      "FFFFCFFFFFFF",
      "FFFFFFFFFFFF",
    ]),
    playerStart: { x: 5, y: 8 },
    npcs: [
      { id: "king-guard", name: "Captain", position: { x: 5, y: 2 }, sprite: "king",
        dialog: ["The King's life is in danger!", "An assassin has breached the inner sanctum.", "Only a legendary warrior can stop them!"],
        questId: "warrior-kings-guard",
      },
    ],
  },

  "Astral Observatory": {
    name: "Astral Observatory",
    width: 12, height: 10,
    tiles: makeGrid([
      "MMMMMMMMMMMM",
      "MCCCTTTTCCCM",
      "MCTHHTTHHTCM",
      "MCTTTTTTTTCM",
      "MCTTTTTTTTCM",
      "MCTTTTTTTTCM",
      "MCTHHTTHHTCM",
      "MCCCTTTTCCCM",
      "MMMMHMMHMMMM",
      "MMMMMMMMMMMM",
    ]),
    playerStart: { x: 5, y: 8 },
    npcs: [
      { id: "astronomer", name: "Grand Astronomer", position: { x: 5, y: 3 }, sprite: "wizard",
        dialog: ["The astral plane has torn open!", "We are being consumed by the void.", "You must close the rift!"],
        questId: "mage-astral-plane",
      },
    ],
  },

  "Celestial Shrine": {
    name: "Celestial Shrine",
    width: 12, height: 10,
    tiles: makeGrid([
      "WWWWWWWWWWWW",
      "WWTTTTTTTTWW",
      "WWTHTTTTHTWW",
      "WWTTTTTTTTWW",
      "WWTTHHHHTTWW",
      "WWTTHHHHTTWW",
      "WWTTTTTTTTWW",
      "WWTHTTTTHTWW",
      "WWTTTWWTTTWW",
      "WWWWWWWWWWWW",
    ]),
    playerStart: { x: 5, y: 8 },
    npcs: [
      { id: "prophet", name: "High Prophet", position: { x: 5, y: 3 }, sprite: "priest",
        dialog: ["The celestial guardian has fallen to corruption.", "Our holy shrine is defiled.", "Purify the guardian and save our souls!"],
        questId: "priest-celestial-shrine",
      },
    ],
  },
};

export function getQuestMap(region: string): QuestMapData | null {
  return QUEST_MAPS[region] || null;
}
