import type { QuestMapData } from "../types/game";

function makeGrid(rows: string[]): QuestMapData["tiles"] {
  const tileMap: Record<string, QuestMapData["tiles"][0][0]> = {
    "G": "grass", "P": "path", "W": "water", "M": "mountain",
    "F": "forest", "T": "town", "C": "cave", "L": "lava",
  };
  return rows.map(row => row.split("").map(c => tileMap[c] || "grass"));
}

const r = (c: string, n: number) => c.repeat(Math.max(0, n));

export const QUEST_MAPS: Record<string, QuestMapData> = {
  // ── OUTDOOR MAPS (30×20) ─────────────────────────────────────────────────
  "Hub Town": {
    name: "Hub Town",
    mapType: "town" as const,
    width: 30, height: 20,
    tiles: makeGrid([
      `G${r('T', 12)}${r('P', 4)}${r('T', 12)}G`,
      `G${r('T', 12)}${r('P', 4)}${r('T', 12)}G`,
      `G${r('T', 12)}${r('P', 4)}${r('T', 12)}G`,
      `G${r('T', 8)}${r('P', 12)}${r('T', 8)}G`,
      `G${r('T', 8)}${r('P', 12)}${r('T', 8)}G`,
      `G${r('T', 8)}${r('P', 4)}${r('T', 4)}${r('P', 4)}${r('T', 8)}G`,
      `G${r('T', 8)}${r('P', 4)}${r('T', 4)}${r('P', 4)}${r('T', 8)}G`,
      `G${r('P', 28)}G`,
      `G${r('P', 10)}${r('T', 8)}${r('P', 10)}G`,
      `G${r('P', 10)}${r('T', 8)}${r('P', 10)}G`,
      `G${r('P', 28)}G`,
      `G${r('P', 10)}${r('T', 8)}${r('P', 10)}G`,
      `G${r('P', 10)}${r('T', 8)}${r('P', 10)}G`,
      `G${r('T', 8)}${r('P', 4)}${r('T', 4)}${r('P', 4)}${r('T', 8)}G`,
      `G${r('T', 8)}${r('P', 4)}${r('T', 4)}${r('P', 4)}${r('T', 8)}G`,
      `G${r('T', 8)}${r('P', 12)}${r('T', 8)}G`,
      `G${r('T', 8)}${r('P', 12)}${r('T', 8)}G`,
      `G${r('T', 12)}${r('P', 4)}${r('T', 12)}G`,
      `G${r('T', 12)}${r('P', 4)}${r('T', 12)}G`,
      `G${r('T', 12)}${r('P', 4)}${r('T', 12)}G`,
    ]),
    playerStart: { x: 15, y: 10 },
    npcs: [
      { id: "elder-hub", name: "Grand Elder", position: { x: 15, y: 4 }, sprite: "elder",
        dialog: ["Welcome to Vibe City, traveler.", "We have many tasks for someone of your talent."],
      },
      { id: "cleric-hub", name: "High Priestess", position: { x: 5, y: 10 }, sprite: "priest",
        dialog: ["The light shines upon you.", "Speak with me if you follow the path of the priest."],
        questId: "priest-plague",
      },
      { id: "knight-hub", name: "Captain of the Guard", position: { x: 24, y: 10 }, sprite: "knight",
        dialog: ["Keep your weapon ready, soldier.", "Warriors should report to me for duty!"],
        questId: "warrior-village",
      },
      { id: "wizard-hub", name: "Archmage", position: { x: 15, y: 15 }, sprite: "wizard",
        dialog: ["I sense great potential in you.", "Mages who seek knowledge should talk to me."],
        questId: "mage-apprentice",
      },
      { id: "guild-master", name: "Guild Master", position: { x: 20, y: 9 }, sprite: "knight",
        dialog: ["Greetings, adventurer!", "The Adventurer's Guild is always looking for talent."],
        service: "guild",
      },
      { id: "merchant-hub", name: "Quartermaster Bronn", position: { x: 10, y: 9 }, sprite: "merchant",
        dialog: ["Fresh supplies for the road.", "If you need gear or provisions, I can help."],
        service: "shop",
      },
    ],
  },

  "Northern Field": {
    name: "Northern Field",
    mapType: "field" as const,
    width: 28, height: 18,
    tiles: makeGrid([
      r('F', 28),
      `F${r('T', 26)}F`,
      `FT${r('G', 24)}TF`,
      `FTG${r('P', 22)}GTF`,
      `FTGP${r('T', 20)}PGTF`,
      `FTGP${r('G', 20)}PGTF`,
      `FTGPG${r('P', 18)}GPGTF`,
      `FTGPG${r('T', 18)}GPGTF`,
      `FTGPGT${r('G', 16)}TGPGTF`,
      `FTGPGT${r('G', 16)}TGPGTF`,
      `FTGPGT${r('G', 16)}TGPGTF`,
      `FTGPGT${r('G', 16)}TGPGTF`,
      `FTGPG${r('T', 18)}GPGTF`,
      `FTGPG${r('P', 18)}GPGTF`,
      `FTGP${r('G', 20)}PGTF`,
      `FTGP${r('T', 20)}PGTF`,
      `FT${r('G', 24)}TF`,
      r('F', 28),
    ]),
    playerStart: { x: 5, y: 9 },
    npcs: [
      { id: "elder", name: "Field Elder", position: { x: 14, y: 3 }, sprite: "elder",
        dialog: ["Welcome, adventurer. Our village is in danger.", "Will you help us?"],
      },
      { id: "guard", name: "Gate Guard", position: { x: 7, y: 9 }, sprite: "guard",
        dialog: ["Halt! The road ahead is dangerous.", "We need a brave warrior to defend our gates!"],
        questId: "warrior-village",
      },
      { id: "merchant-nv", name: "Traveling Merchant", position: { x: 20, y: 6 }, sprite: "merchant",
        dialog: ["Greetings! Be careful out there.", "I've stocked what this village needs to survive."],
        service: "shop",
      },
      { id: "priest-nv", name: "Field Priest", position: { x: 14, y: 6 }, sprite: "priest",
        dialog: ["The village needs protection from evil.", "Can you help perform a blessing ritual?"],
        questId: "priest-blessing",
      },
    ],
  },

  "Whispering Woods": {
    name: "Whispering Woods",
    mapType: "field" as const,
    width: 30, height: 20,
    tiles: makeGrid([
      r('F', 30),
      r('F', 30),
      `FF${r('G', 4)}FF${r('G', 4)}FF${r('G', 4)}FF${r('G', 4)}FFFFF`,
      `FFG${r('P', 3)}GFFG${r('P', 3)}GFFG${r('P', 3)}GFFG${r('P', 3)}GFFF`,
      `FFP${r('F', 4)}P${r('F', 4)}PP${r('F', 4)}P${r('F', 4)}PPFF`,
      `FFP${r('F', 24)}PFF`,
      `FFP${r('F', 24)}PFF`,
      `FFP${r('F', 5)}G${r('F', 12)}G${r('F', 5)}PFF`,
      `FFP${r('F', 4)}GP${r('F', 10)}PG${r('F', 4)}PFF`,
      `FFP${r('F', 4)}P${r('F', 12)}P${r('F', 4)}PFF`,
      `FFP${r('F', 4)}P${r('F', 12)}P${r('F', 4)}PFF`,
      `FFP${r('F', 4)}GP${r('F', 10)}PG${r('F', 4)}PFF`,
      `FFP${r('F', 5)}G${r('F', 12)}G${r('F', 5)}PFF`,
      `FFP${r('F', 24)}PFF`,
      `FFP${r('F', 24)}PFF`,
      `FFG${r('P', 3)}GFFG${r('P', 3)}GFFG${r('P', 3)}GFFG${r('P', 3)}GFFF`,
      `FF${r('G', 4)}FF${r('G', 4)}FF${r('G', 4)}FF${r('G', 4)}FFFFF`,
      r('F', 30),
      r('F', 30),
      r('F', 30),
    ]),
    playerStart: { x: 5, y: 17 },
    npcs: [
      { id: "fairy-w", name: "Forest Fairy", position: { x: 12, y: 8 }, sprite: "fairy",
        dialog: ["The woods whisper of a lost apprentice...", "Find them before the forest claims them!"],
        questId: "mage-apprentice",
      },
      { id: "wizard-w", name: "Forest Sage", position: { x: 22, y: 3 }, sprite: "wizard",
        dialog: ["I sensed wild magic from the old library.", "Only a skilled mage can handle this."],
        questId: "mage-library",
      },
    ],
  },

  "Mountain Pass": {
    name: "Mountain Pass",
    mapType: "field" as const,
    width: 28, height: 18,
    tiles: makeGrid([
      r('M', 28),
      r('M', 28),
      `MM${r('G', 4)}MM${r('G', 4)}MM${r('G', 4)}MM${r('G', 4)}MMMM`,
      `MMG${r('P', 3)}GMM${r('P', 3)}MMG${r('P', 3)}GMM${r('P', 3)}GMMM`,
      `MMP${r('M', 4)}P${r('M', 4)}PP${r('M', 4)}P${r('M', 3)}PMM`,
      `MMP${r('G', 20)}PMM`,
      `MMP${r('G', 5)}MM${r('G', 8)}MM${r('G', 5)}PMM`,
      `MMP${r('G', 4)}P${r('G', 10)}P${r('G', 4)}PMM`,
      `MMP${r('G', 4)}P${r('G', 10)}P${r('G', 4)}PMM`,
      `MMP${r('G', 4)}P${r('G', 10)}P${r('G', 4)}PMM`,
      `MMP${r('G', 4)}P${r('G', 10)}P${r('G', 4)}PMM`,
      `MMP${r('G', 4)}P${r('G', 10)}P${r('G', 4)}PMM`,
      `MMP${r('G', 5)}MM${r('G', 8)}MM${r('G', 5)}PMM`,
      `MMP${r('G', 20)}PMM`,
      `MMP${r('M', 20)}PMM`,
      `MM${r('G', 4)}MM${r('G', 4)}MM${r('G', 4)}MM${r('G', 4)}MMMM`,
      r('M', 28),
      r('M', 28),
    ]),
    playerStart: { x: 3, y: 8 },
    npcs: [
      { id: "miner", name: "Frightened Miner", position: { x: 14, y: 3 }, sprite: "villager",
        dialog: ["Something massive has awakened in the mountain!", "We need magical help to deal with it!"],
        questId: "mage-elemental",
      },
    ],
  },

  "Trade Route": {
    name: "Trade Route",
    mapType: "field" as const,
    width: 30, height: 18,
    tiles: makeGrid([
      r('G', 30),
      `G${r('F', 28)}G`,
      `GF${r('G', 26)}FG`,
      `GFG${r('P', 24)}GFG`,
      `GFG${r('P', 5)}${r('F', 14)}${r('P', 5)}GFG`,
      `GFG${r('P', 3)}${r('F', 18)}${r('P', 3)}GFG`,
      `GFG${r('P', 3)}${r('F', 18)}${r('P', 3)}GFG`,
      `GFG${r('P', 24)}GFG`,
      `GFG${r('P', 3)}${r('F', 18)}${r('P', 3)}GFG`,
      `GFG${r('P', 3)}${r('F', 18)}${r('P', 3)}GFG`,
      `GFG${r('P', 3)}${r('F', 18)}${r('P', 3)}GFG`,
      `GFG${r('P', 24)}GFG`,
      `GFG${r('P', 3)}${r('F', 18)}${r('P', 3)}GFG`,
      `GFG${r('P', 3)}${r('F', 18)}${r('P', 3)}GFG`,
      `GFG${r('P', 24)}GFG`,
      `GF${r('G', 26)}FG`,
      `G${r('F', 28)}G`,
      r('G', 30),
    ]),
    playerStart: { x: 3, y: 4 },
    npcs: [
      { id: "merchant-tr", name: "Scared Merchant", position: { x: 15, y: 4 }, sprite: "merchant",
        dialog: ["Please help! Wolves have made a nest near the road!", "We need someone strong to clear the way!"],
        questId: "warrior-monster",
      },
    ],
  },

  "Training Grounds": {
    name: "Training Grounds",
    mapType: "field" as const,
    width: 28, height: 18,
    tiles: makeGrid([
      r('G', 28),
      `G${r('P', 26)}G`,
      `GP${r('T', 24)}PG`,
      `GPT${r('P', 22)}TPG`,
      `GPTP${r('G', 20)}PTPG`,
      `GPTP${r('G', 7)}T${r('G', 4)}T${r('G', 7)}PTPG`,
      `GPTP${r('G', 7)}T${r('G', 4)}T${r('G', 7)}PTPG`,
      `GPTP${r('G', 7)}T${r('G', 4)}T${r('G', 7)}PTPG`,
      `GPTP${r('P', 20)}PTPG`,
      `GPTP${r('P', 20)}PTPG`,
      `GPTP${r('G', 7)}T${r('G', 4)}T${r('G', 7)}PTPG`,
      `GPTP${r('G', 7)}T${r('G', 4)}T${r('G', 7)}PTPG`,
      `GPTP${r('G', 7)}T${r('G', 4)}T${r('G', 7)}PTPG`,
      `GPTP${r('G', 20)}PTPG`,
      `GPT${r('P', 22)}TPG`,
      `GP${r('T', 24)}PG`,
      `G${r('P', 26)}G`,
      r('G', 28),
    ]),
    playerStart: { x: 3, y: 16 },
    npcs: [
      { id: "knight-tg", name: "Honor Knight", position: { x: 14, y: 9 }, sprite: "knight",
        dialog: ["You dare enter my arena?", "Prove your worth in combat, warrior!"],
        questId: "warrior-duel",
      },
    ],
  },

  "Dark Forest": {
    name: "Dark Forest",
    mapType: "field" as const,
    width: 30, height: 20,
    tiles: makeGrid([
      r('F', 30),
      r('F', 30),
      `FF${r('G', 4)}F${r('G', 4)}F${r('G', 8)}F${r('G', 4)}FFFF`,
      `FFG${r('P', 4)}G${r('F', 4)}G${r('P', 4)}G${r('F', 4)}GFF`,
      `FFP${r('F', 24)}PFF`,
      `FFP${r('F', 4)}G${r('F', 4)}G${r('F', 4)}G${r('F', 4)}G${r('F', 4)}PFF`,
      `FFP${r('F', 24)}PFF`,
      `FFP${r('F', 5)}G${r('F', 12)}G${r('F', 5)}PFF`,
      `FFP${r('F', 4)}GP${r('F', 10)}PG${r('F', 4)}PFF`,
      `FFP${r('F', 4)}P${r('G', 12)}P${r('F', 4)}PFF`,
      `FFP${r('F', 4)}P${r('G', 12)}P${r('F', 4)}PFF`,
      `FFP${r('F', 4)}GP${r('F', 10)}PG${r('F', 4)}PFF`,
      `FFP${r('F', 5)}G${r('F', 12)}G${r('F', 5)}PFF`,
      `FFP${r('F', 24)}PFF`,
      `FFP${r('F', 4)}G${r('F', 4)}G${r('F', 8)}G${r('F', 2)}PFF`,
      `FFG${r('P', 4)}G${r('F', 4)}G${r('P', 4)}G${r('F', 4)}GFF`,
      `FF${r('G', 4)}F${r('G', 4)}F${r('G', 8)}F${r('G', 4)}FFFF`,
      r('F', 30),
      r('F', 30),
      r('F', 30),
    ]),
    playerStart: { x: 5, y: 17 },
    npcs: [
      { id: "scout-df", name: "Village Scout", position: { x: 13, y: 10 }, sprite: "guard",
        dialog: ["I've been tracking the orc war camp!", "Be careful — they're well armed!"],
        questId: "warrior-orc-camp",
      },
    ],
  },

  "Dragon Peak": {
    name: "Dragon Peak",
    mapType: "field" as const,
    width: 28, height: 18,
    tiles: makeGrid([
      r('M', 28),
      r('M', 28),
      `MM${r('G', 6)}${r('M', 4)}${r('G', 6)}${r('M', 4)}${r('G', 4)}MM`,
      `MMG${r('P', 4)}GM${r('M', 2)}G${r('P', 4)}G${r('M', 2)}G${r('P', 4)}GMM`,
      `MMP${r('M', 4)}P${r('M', 4)}P${r('M', 4)}P${r('M', 4)}PMM`,
      `MMP${r('G', 20)}PMM`,
      `MMP${r('G', 4)}M${r('G', 10)}M${r('G', 4)}PMM`,
      `MMP${r('G', 3)}MP${r('G', 8)}PM${r('G', 3)}PMM`,
      `MMP${r('G', 3)}P${r('G', 10)}P${r('G', 3)}PMM`,
      `MMP${r('G', 3)}P${r('G', 10)}P${r('G', 3)}PMM`,
      `MMP${r('G', 3)}P${r('G', 10)}P${r('G', 3)}PMM`,
      `MMP${r('G', 3)}MP${r('G', 8)}PM${r('G', 3)}PMM`,
      `MMP${r('G', 4)}M${r('G', 10)}M${r('G', 4)}PMM`,
      `MMP${r('G', 20)}PMM`,
      `MMP${r('M', 20)}PMM`,
      `MM${r('G', 6)}${r('M', 4)}${r('G', 6)}${r('M', 4)}${r('G', 4)}MM`,
      r('M', 28),
      r('M', 28),
    ]),
    playerStart: { x: 3, y: 9 },
    npcs: [
      { id: "hermit-dp", name: "Mountain Hermit", position: { x: 14, y: 3 }, sprite: "elder",
        dialog: ["You seek the wyvern? It nests at the peak.", "Use the terrain wisely!"],
        questId: "warrior-dragon-lair",
      },
    ],
  },

  "Southern Field": {
    name: "Southern Field",
    mapType: "field" as const,
    width: 28, height: 18,
    tiles: makeGrid([
      r('G', 28),
      `G${r('P', 26)}G`,
      `GP${r('T', 24)}PG`,
      `GPT${r('P', 22)}TPG`,
      `GPTP${r('G', 20)}PTPG`,
      `GPTP${r('G', 20)}PTPG`,
      `GPTP${r('P', 20)}PTPG`,
      `GPTP${r('T', 7)}${r('G', 6)}${r('T', 7)}PTPG`,
      `GPTP${r('T', 7)}${r('G', 6)}${r('T', 7)}PTPG`,
      `GPTP${r('G', 20)}PTPG`,
      `GPTP${r('G', 20)}PTPG`,
      `GPTP${r('P', 20)}PTPG`,
      `GPTP${r('T', 20)}PTPG`,
      `GPTP${r('G', 20)}PTPG`,
      `GPT${r('P', 22)}TPG`,
      `GP${r('T', 24)}PG`,
      `G${r('P', 26)}G`,
      r('G', 28),
    ]),
    playerStart: { x: 3, y: 9 },
    npcs: [
      { id: "healer-sv", name: "Field Healer", position: { x: 14, y: 8 }, sprite: "priest",
        dialog: ["The plague is spreading fast!", "Can you purify the water source?"],
        questId: "priest-plague",
      },
    ],
  },

  // ── DUNGEON / INTERIOR MAPS (~18×14) ─────────────────────────────────────
  "Abandoned Church": {
    name: "Abandoned Church",
    mapType: "dungeon" as const,
    width: 18, height: 14,
    tiles: makeGrid([
      r('G', 18),
      `G${r('C', 16)}G`,
      `GC${r('P', 14)}CG`,
      `GC${r('P', 14)}CG`,
      `GC${r('P', 14)}CG`,
      `GC${r('P', 6)}C${r('P', 6)}CG`,
      `GC${r('P', 6)}C${r('P', 6)}CG`,
      `GC${r('P', 6)}C${r('P', 6)}CG`,
      `GC${r('P', 14)}CG`,
      `GC${r('P', 14)}CG`,
      `GC${r('P', 14)}CG`,
      `GC${r('P', 14)}CG`,
      `G${r('C', 16)}G`,
      r('G', 18),
    ]),
    playerStart: { x: 3, y: 7 },
    npcs: [
      { id: "spirit-ac", name: "Monastery Keeper", position: { x: 9, y: 4 }, sprite: "elder",
        dialog: ["The old church has been haunted for years.", "Only divine light can bring it peace."],
        questId: "priest-ghost",
      },
    ],
  },

  "Sacred Catacombs": {
    name: "Sacred Catacombs",
    mapType: "dungeon" as const,
    width: 18, height: 14,
    tiles: makeGrid([
      r('C', 18),
      `C${r('P', 16)}C`,
      `CP${r('C', 6)}P${r('C', 6)}PC`,
      `C${r('P', 16)}C`,
      `CP${r('G', 14)}PC`,
      `CP${r('G', 14)}PC`,
      `CP${r('G', 14)}PC`,
      `CP${r('G', 14)}PC`,
      `CP${r('G', 14)}PC`,
      `CP${r('G', 14)}PC`,
      `C${r('P', 16)}C`,
      `CP${r('C', 6)}P${r('C', 6)}PC`,
      `C${r('P', 16)}C`,
      r('C', 18),
    ]),
    playerStart: { x: 3, y: 7 },
    npcs: [
      { id: "priest-sc", name: "Tomb Guardian", position: { x: 9, y: 3 }, sprite: "priest",
        dialog: ["The undead have broken free!", "Your divine power is needed to seal them!"],
        questId: "priest-undead-crypt",
      },
    ],
  },

  "Cursed Ruins": {
    name: "Cursed Ruins",
    mapType: "dungeon" as const,
    width: 18, height: 14,
    tiles: makeGrid([
      r('C', 18),
      `C${r('L', 16)}C`,
      `CL${r('C', 6)}L${r('C', 6)}LC`,
      `C${r('L', 16)}C`,
      `CL${r('G', 14)}LC`,
      `CL${r('G', 14)}LC`,
      `CL${r('G', 14)}LC`,
      `CL${r('G', 14)}LC`,
      `CL${r('G', 14)}LC`,
      `CL${r('G', 14)}LC`,
      `C${r('L', 16)}C`,
      `CL${r('C', 6)}L${r('C', 6)}LC`,
      `C${r('L', 16)}C`,
      r('C', 18),
    ]),
    playerStart: { x: 3, y: 7 },
    npcs: [
      { id: "angel-cr", name: "Fallen Angel", position: { x: 9, y: 3 }, sprite: "fairy",
        dialog: ["A demon portal has opened in the ruins!", "You must channel divine power to seal it!"],
        questId: "priest-demon-portal",
      },
    ],
  },

  "Crystal Caverns": {
    name: "Crystal Caverns",
    mapType: "dungeon" as const,
    width: 18, height: 14,
    tiles: makeGrid([
      r('C', 18),
      `C${r('G', 16)}C`,
      `CG${r('P', 14)}GC`,
      `CGP${r('G', 12)}PGC`,
      `CGP${r('G', 5)}P${r('G', 5)}PGC`,
      `CGP${r('G', 5)}P${r('G', 5)}PGC`,
      `CGP${r('G', 12)}PGC`,
      `CGP${r('G', 12)}PGC`,
      `CGP${r('G', 5)}P${r('G', 5)}PGC`,
      `CGP${r('G', 5)}P${r('G', 5)}PGC`,
      `CGP${r('G', 12)}PGC`,
      `CG${r('P', 14)}GC`,
      `C${r('G', 16)}C`,
      r('C', 18),
    ]),
    playerStart: { x: 3, y: 7 },
    npcs: [
      { id: "miner-cc", name: "Crystal Miner", position: { x: 9, y: 5 }, sprite: "villager",
        dialog: ["Strange crystals attract dangerous creatures.", "Can you use your magic to help us?"],
        questId: "mage-crystalcave",
      },
    ],
  },

  "Shadow Tower": {
    name: "Shadow Tower",
    mapType: "dungeon" as const,
    width: 18, height: 14,
    tiles: makeGrid([
      r('F', 18),
      `F${r('C', 16)}F`,
      `FC${r('G', 14)}CF`,
      `FC${r('P', 14)}CF`,
      `FCG${r('P', 5)}C${r('P', 5)}GCF`,
      `FCG${r('P', 5)}C${r('P', 5)}GCF`,
      `FC${r('P', 14)}CF`,
      `FC${r('P', 14)}CF`,
      `FCG${r('P', 5)}C${r('P', 5)}GCF`,
      `FCG${r('P', 5)}C${r('P', 5)}GCF`,
      `FC${r('P', 14)}CF`,
      `FC${r('G', 14)}CF`,
      `F${r('C', 16)}F`,
      r('F', 18),
    ]),
    playerStart: { x: 3, y: 7 },
    npcs: [
      { id: "wizard-st", name: "Tower Sentinel", position: { x: 9, y: 3 }, sprite: "wizard",
        dialog: ["A rogue mage has seized the watchtower!", "Only another mage can challenge him!"],
        questId: "mage-tower",
      },
    ],
  },

  "Capital City": {
    name: "Capital City",
    mapType: "town" as const,
    width: 18, height: 14,
    tiles: makeGrid([
      r('T', 18),
      `T${r('P', 16)}T`,
      `TP${r('T', 14)}PT`,
      `TP${r('T', 14)}PT`,
      `TP${r('T', 4)}G${r('T', 4)}G${r('T', 4)}PT`,
      `TP${r('T', 14)}PT`,
      `TP${r('P', 14)}PT`,
      `TP${r('T', 14)}PT`,
      `TP${r('T', 4)}G${r('T', 4)}G${r('T', 4)}PT`,
      `TP${r('T', 14)}PT`,
      `TP${r('T', 14)}PT`,
      `TP${r('T', 14)}PT`,
      `T${r('P', 16)}T`,
      r('T', 18),
    ]),
    playerStart: { x: 9, y: 12 },
    npcs: [
      { id: "king-guard", name: "Captain", position: { x: 9, y: 3 }, sprite: "king",
        dialog: ["The King's life is in danger!", "Only a legendary warrior can stop the assassin!"],
        questId: "warrior-kings-guard",
      },
    ],
  },

  "Astral Observatory": {
    name: "Astral Observatory",
    mapType: "dungeon" as const,
    width: 18, height: 14,
    tiles: makeGrid([
      r('M', 18),
      `M${r('C', 16)}M`,
      `MC${r('T', 14)}CM`,
      `MC${r('T', 5)}G${r('T', 3)}G${r('T', 4)}CM`,
      `MC${r('T', 14)}CM`,
      `MC${r('T', 14)}CM`,
      `MC${r('T', 5)}G${r('T', 2)}G${r('T', 5)}CM`,
      `MC${r('T', 14)}CM`,
      `MC${r('T', 14)}CM`,
      `MC${r('T', 5)}G${r('T', 3)}G${r('T', 4)}CM`,
      `MC${r('T', 14)}CM`,
      `MC${r('T', 14)}CM`,
      `M${r('C', 16)}M`,
      r('M', 18),
    ]),
    playerStart: { x: 9, y: 12 },
    npcs: [
      { id: "astronomer", name: "Grand Astronomer", position: { x: 9, y: 3 }, sprite: "wizard",
        dialog: ["The astral plane has torn open!", "You must close the rift!"],
        questId: "mage-astral-plane",
      },
    ],
  },

  "Celestial Shrine": {
    name: "Celestial Shrine",
    mapType: "dungeon" as const,
    width: 18, height: 14,
    tiles: makeGrid([
      r('W', 18),
      `W${r('T', 16)}W`,
      `WT${r('T', 6)}G${r('T', 7)}TW`,
      `W${r('T', 16)}W`,
      `WT${r('G', 4)}T${r('G', 4)}T${r('G', 4)}TW`,
      `W${r('T', 16)}W`,
      `W${r('T', 16)}W`,
      `W${r('T', 16)}W`,
      `WT${r('G', 4)}T${r('G', 4)}T${r('G', 4)}TW`,
      `W${r('T', 16)}W`,
      `WT${r('T', 6)}G${r('T', 7)}TW`,
      `W${r('T', 16)}W`,
      `W${r('T', 16)}W`,
      r('W', 18),
    ]),
    playerStart: { x: 9, y: 12 },
    npcs: [
      { id: "prophet", name: "High Prophet", position: { x: 9, y: 3 }, sprite: "priest",
        dialog: ["The celestial guardian has fallen to corruption.", "Purify the guardian and save our souls!"],
        questId: "priest-celestial-shrine",
      },
    ],
  },
};

export function getQuestMap(region: string): QuestMapData | null {
  return QUEST_MAPS[region] || null;
}
